package main

import (
	"fmt"
	"os"
	"path/filepath"
)

func main() {
	out := os.Getenv("BU1LD_GO_GENERATE_OUT")
	if out == "" {
		out = filepath.Join("build", "generated", "go")
	}
	if err := os.MkdirAll(out, 0o755); err != nil {
		panic(err)
	}
	file := filepath.Join(out, "message.txt")
	if err := os.WriteFile(file, []byte("generated by go generate\n"), 0o644); err != nil {
		panic(err)
	}
	fmt.Println("generated", file)
}
