package org.bu1ld.plugins.java;

import com.google.common.collect.ImmutableMap;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import lombok.val;
import org.apache.commons.io.FileUtils;

final class DependencyLock {
    static final String MODE_OFF = "off";
    static final String MODE_READ = "read";
    static final String MODE_WRITE = "write";

    private DependencyLock() {
    }

    static void apply(Path workDir, String lockFile, String mode, List<ResolvedArtifact> artifacts) throws IOException {
        if (lockFile == null || lockFile.isBlank() || mode == null || mode.isBlank() || MODE_OFF.equalsIgnoreCase(mode)) {
            return;
        }

        val path = resolve(workDir, lockFile);
        switch (mode.toLowerCase()) {
            case MODE_READ -> verify(path, artifacts);
            case MODE_WRITE, "update" -> write(path, artifacts);
            default -> throw new IllegalArgumentException("dependency_lock_mode must be off, read, write, or update");
        }
    }

    private static void verify(Path path, List<ResolvedArtifact> artifacts) throws IOException {
        if (!Files.isRegularFile(path)) {
            throw new IllegalStateException("dependency lock file does not exist: " + path);
        }
        val locked = read(path);
        for (val artifact : artifacts) {
            val expected = locked.get(artifact.coordinate());
            if (expected == null) {
                throw new IllegalStateException("dependency lock is missing " + artifact.coordinate());
            }
            val actual = sha256(artifact.path());
            if (!expected.equalsIgnoreCase(actual)) {
                throw new IllegalStateException(
                    "dependency lock checksum mismatch for " + artifact.coordinate() + ": got sha256:" + actual
                        + ", want sha256:" + expected
                );
            }
        }
    }

    private static void write(Path path, List<ResolvedArtifact> artifacts) throws IOException {
        val locked = new LinkedHashMap<String, String>(Files.isRegularFile(path) ? read(path) : ImmutableMap.of());
        for (val artifact : artifacts) {
            locked.put(artifact.coordinate(), sha256(artifact.path()));
        }

        val entries = new ArrayList<Map.Entry<String, String>>(locked.entrySet());
        entries.sort(Comparator.comparing(Map.Entry::getKey));

        val builder = new StringBuilder();
        builder.append("# Generated by bu1ld Java plugin.\n\n");
        for (val entry : entries) {
            builder
                .append("[[artifact]]\n")
                .append("coordinate = \"")
                .append(escape(entry.getKey()))
                .append("\"\n")
                .append("sha256 = \"")
                .append(entry.getValue())
                .append("\"\n\n");
        }

        FileUtils.forceMkdirParent(path.toFile());
        Files.writeString(path, builder.toString(), StandardCharsets.UTF_8);
    }

    private static Map<String, String> read(Path path) throws IOException {
        val locked = new LinkedHashMap<String, String>();
        String coordinate = null;
        for (val rawLine : Files.readAllLines(path, StandardCharsets.UTF_8)) {
            val line = rawLine.trim();
            if (line.startsWith("coordinate")) {
                coordinate = unquote(value(line));
            } else if (line.startsWith("sha256") && coordinate != null) {
                locked.put(coordinate, unquote(value(line)));
                coordinate = null;
            }
        }
        return locked;
    }

    private static Path resolve(Path workDir, String lockFile) {
        val path = Path.of(lockFile);
        if (path.isAbsolute()) {
            return path.normalize();
        }
        return workDir.resolve(path).normalize();
    }

    private static String value(String line) {
        val index = line.indexOf('=');
        if (index < 0) {
            throw new IllegalArgumentException("invalid dependency lock line: " + line);
        }
        return line.substring(index + 1).trim();
    }

    private static String escape(String value) {
        return value.replace("\\", "\\\\").replace("\"", "\\\"");
    }

    private static String unquote(String value) {
        var text = value;
        if (text.startsWith("\"") && text.endsWith("\"") && text.length() >= 2) {
            text = text.substring(1, text.length() - 1);
        }
        return text.replace("\\\"", "\"").replace("\\\\", "\\");
    }

    private static String sha256(Path path) throws IOException {
        try {
            val digest = MessageDigest.getInstance("SHA-256");
            try (InputStream input = Files.newInputStream(path)) {
                val buffer = new byte[8192];
                int read;
                while ((read = input.read(buffer)) >= 0) {
                    digest.update(buffer, 0, read);
                }
            }
            val hash = digest.digest();
            val builder = new StringBuilder(hash.length * 2);
            for (val item : hash) {
                builder.append("%02x".formatted(item & 0xff));
            }
            return builder.toString();
        } catch (NoSuchAlgorithmException e) {
            throw new IllegalStateException("SHA-256 is not available", e);
        }
    }
}
